Added test to check for onhm-runners source.

diff --git a/nhmusgs-base/test/system b/nhmusgs-base/test/system
--- a/nhmusgs-base/test/system
+++ b/nhmusgs-base/test/system
@@ -7,9 +7,29 @@
 #  Author - Andrew Halper <ashalper@usgs.gov>
 #
 
+# create temp. file path for package listing
 dpkg_query_tmp=$(mktemp /tmp/dpkg-query.XXX)
+
+# query package database on container, and save list to temp. file
 docker run nhmusgs/base /usr/bin/dpkg-query -W -f='${Status} ${Package}\n' > $dpkg_query_tmp
-diff dpkg-query.txt $dpkg_query_tmp
-status=$?
-rm -f $dpkg_query_tmp
-exit $status
+
+# compare expected package list with actual package list
+diff dpkg-query.txt $dpkg_query_tmp > /dev/null 2>&1
+
+status=$?			# preserve "diff" exit status
+
+rm -f $dpkg_query_tmp		# remove temp. file
+
+# check package list comparison success/failure
+if [ $status != 0 ]; then
+    echo 'dpkg package verificaton failed'
+    exit $status
+fi
+
+# if the onhm-runners source is not present...
+if [ `docker run nhmusgs/base ls -d /usr/local/src/onhm-runners` != \
+    /usr/local/src/onhm-runners ]; then
+    # ...fail
+    echo 'onhm-runners source check failed'
+    exit 1
+fi
